import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import numpy as np
from datetime import datetime, timedelta
import pymongo
import pickle
import bson
import subprocess
import sys

# Other external scripts
import lst1_mongodb_example
import utils


dict_caco_states = {0 : "OFF", 1 : "DATA_MONITORING", 2 : "MONITORED", 3 : "SAFE", 4 : "STANDBY",
                    5 : "READY", 6 : "OBSERVING", 7 : "TPOINT", 8 : "UNDEFINED", 9 : "TRANSITIONAL", 10 : "ERROR"}
dict_caco_state_colors = {0 : "k", 1 : "darkviolet", 2 : "darkviolet", 3 : "lime", 4 : "gold",
                          5 : "c", 6 : "darkblue", 7 : "b", 8 : "r", 9 : "darkorange", 10 : "r"}


def main(query_property):

    client_tcu  = pymongo.MongoClient("127.0.0.1:27017")
    client_caco = pymongo.MongoClient("127.0.0.1:27018")
    
    variable_tcu = "CameraControl_FSM_state"
    tstart = datetime.fromisoformat("2024-02-25-00:00:00")
    tstop  = datetime.fromisoformat("2024-04-01-00:00:00")
    
    
    out_tcu = lst1_mongodb_example.get_entries(client_tcu, variable_tcu, astropy_time=False, tstart=tstart, tstop=tstop)
    date_tcu, value_tcu = np.array(out_tcu["time"]), np.array(out_tcu["value"])
    
    value_str_tcu = np.array([dict_caco_states[v] for v in value_tcu])


    # Creating a timespan dictionary for each key
    timespans_dict = {}
    for key in dict_caco_states.keys():
        timespans_dict[key] = {"tstart" : [], "tstop" : [], "tspan" : []}
    
    before_state = value_tcu[0]
    initial_time = date_tcu[0]
    for i in range(len(value_tcu))[1:]:
        
        actual_state = value_tcu[i]
    
        if before_state != actual_state:
            final_time = date_tcu[i]
    
            timespans_dict[actual_state]["tstart"].append(initial_time)
            timespans_dict[actual_state]["tstop"].append(final_time)
            
            timespans_dict[actual_state]["tspan"].append((final_time - initial_time).total_seconds())
    
            initial_time = date_tcu[i]
            
        before_state = actual_state


    camera_related_tcu_properties = ['CalibrationBox_BG_InterCalibration_Mean',
     'CalibrationBox_DewPoint',
     'CalibrationBox_Error_BG_InterCalibration_Mean',
     'CalibrationBox_Error_InterCalibration_Mean',
     'CalibrationBox_FSM_state',
     'CalibrationBox_FSM_transition',
     'CalibrationBox_Humidity',
     'CalibrationBox_InterCalibration_Mean',
     'CalibrationBox_LaserErrorCode',
     'CalibrationBox_LaserInfoCode',
     'CalibrationBox_LaserStatus',
     'CalibrationBox_LaserTrigParameters',
     'CalibrationBox_PedStatus',
     'CalibrationBox_PedTrigParameters',
     'CalibrationBox_PowerStatus',
     'CalibrationBox_PowerStatusLR',
     'CalibrationBox_Pressure',
     'CalibrationBox_Temperature',
     'CalibrationBox_WheelPosition',
     'Calibration_CalibrationBox_Humidity',
     'Calibration_CalibrationBox_LaserErrorCode',
     'Calibration_CalibrationBox_LaserInfoCode',
     'Calibration_CalibrationBox_LaserStatus',
     'Calibration_CalibrationBox_LaserTrigParameters',
     'Calibration_CalibrationBox_PowerStatus',
     'Calibration_CalibrationBox_Pressure',
     'Calibration_CalibrationBox_Temperature',
     'Calibration_CalibrationBox_WheelPosition',
     'CameraControl_CBOXControl_state',
     'CameraControl_FSM_is_transit',
     'CameraControl_FSM_is_warm_up',
     'CameraControl_FSM_previous_state',
     'CameraControl_FSM_state',
     'CameraControl_InstrumentProtection_mode',
     'CameraControl_InstrumentProtection_status',
     'CameraControl_MessageAdviser_last_message',
     'CameraControl_ModulesAvailable_CBOX_valid_connection',
     'CameraControl_ModulesAvailable_CLUS_valid_connection',
     'CameraControl_ModulesAvailable_DAQ_valid_connection',
     'CameraControl_ModulesAvailable_ECC_valid_connection',
     'CameraControl_ModulesAvailable_Sphe_valid_connection',
     'CameraControl_ModulesAvailable_TIB_valid_connection',
     'CameraControl_ModulesAvailable_UCTS_valid_connection',
     'CameraControl_ModulesStatus_CLUSCO',
     'CameraControl_ModulesStatus_CS',
     'CameraControl_ModulesStatus_DAQ',
     'CameraControl_ModulesStatus_ECC',
     'CameraControl_ModulesStatus_SIS',
     'CameraControl_ModulesStatus_TIB',
     'CameraControl_ModulesStatus_UCTS',
     'CameraControl_RunUtils_is_test',
     'CameraControl_RunUtils_run_number',
     'CameraControl_UserAdviser_message',
     'CameraControl__ControlLoopTimeStamp',
     'CameraControl_heartbeat_caco_timestamp',
     'CameraControl_heartbeat_enabled',
     'CameraControl_heartbeat_time_limit',
     'CameraControl_heartbeat_times_failed',
     'CameraControl_information_MessageAdviser_last_message',
     'CameraControl_information_error_state',
     'Camera_CalibrationBox_BG_InterCalibration_Mean',
     'Camera_CalibrationBox_DewPoint',
     'Camera_CalibrationBox_Error_BG_InterCalibration_Mean',
     'Camera_CalibrationBox_Error_InterCalibration_Mean',
     'Camera_CalibrationBox_Humidity',
     'Camera_CalibrationBox_InterCalibration_Mean',
     'Camera_CalibrationBox_LaserErrorCode',
     'Camera_CalibrationBox_LaserInfoCode',
     'Camera_CalibrationBox_LaserStatus',
     'Camera_CalibrationBox_LaserTrigParameters',
     'Camera_CalibrationBox_PedRndTrigParameter',
     'Camera_CalibrationBox_PedStatus',
     'Camera_CalibrationBox_PedTrigParameters',
     'Camera_CalibrationBox_PowerStatus',
     'Camera_CalibrationBox_PowerStatusLR',
     'Camera_CalibrationBox_Pressure',
     'Camera_CalibrationBox_Temperature',
     'Camera_CalibrationBox_WheelPosition',
     'Camera_UCTS_ConfigurationParameters_CDTS_MAC_Address',
     'Camera_UCTS_ConfigurationParameters_OPCUA_server_IP_Address',
     'Camera_UCTS_ConfigurationParameters_UCTS_IP_Address',
     'Camera_UCTS_Configuration_UctsIpAddr',
     'Camera_UCTS_FSM_state',
     'Camera_UCTS_FSM_transition',
     'Camera_UCTS_HardwareConfig_state',
     'Camera_UCTS_SNMPParameters_SNMP_Port_Link_Status',
     'Camera_UCTS_SNMPParameters_SNMP_Temperature',
     'Camera_UCTS_SNMPParameters_SNMP_Time_TAI',
     'Camera_UCTS_SNMPParameters_SNMP_Up_Time',
     'Camera_UCTS_SNMPParameters_SNMP_wrpc_Sw_Version',
     'Camera_UCTS_SNMP_BusyCount',
     'Camera_UCTS_SNMP_DstIpAddr',
     'Camera_UCTS_SNMP_DstMacAddr',
     'Camera_UCTS_SNMP_DstPort',
     'Camera_UCTS_SNMP_EventCount',
     'Camera_UCTS_SNMP_PortLinkStatus',
     'Camera_UCTS_SNMP_Status',
     'Camera_UCTS_SNMP_Temperature',
     'Camera_UCTS_SNMP_Throttle',
     'Camera_UCTS_SNMP_TimeTAI',
     'Camera_UCTS_SNMP_UpTime',
     'Camera_UCTS_SNMP_WrpcSwVersion',
     'Camera__ControlLoopTimeStamp',
     'Camera__Enable_Heart_Beat',
     'Camera__Error_Heart_Beat',
     'Camera__Heart_Beat',
     'ECC_FSM_state',
     'ECC_FSM_transition',
     'ECC_Monitoring_AirValve_AirRegulationStatus',
     'ECC_Monitoring_AirValve_AirValveError',
     'ECC_Monitoring_AirValve_AirValveStatus',
     'ECC_Monitoring_Alarm_Status_Alarm_Back_Door',
     'ECC_Monitoring_Alarm_Status_Alarm_Caco_HeartBeat',
     'ECC_Monitoring_Alarm_Status_Alarm_ChillerHeating',
     'ECC_Monitoring_Alarm_Status_Alarm_Current_24V_PSU1',
     'ECC_Monitoring_Alarm_Status_Alarm_Current_24V_PSU2',
     'ECC_Monitoring_Alarm_Status_Alarm_Flowmeter',
     'ECC_Monitoring_Alarm_Status_Alarm_Front_Door',
     'ECC_Monitoring_Alarm_Status_Alarm_General_current',
     'ECC_Monitoring_Alarm_Status_Alarm_Humidity',
     'ECC_Monitoring_Alarm_Status_Alarm_IR',
     'ECC_Monitoring_Alarm_Status_Alarm_Light',
     'ECC_Monitoring_Alarm_Status_Alarm_PDB',
     'ECC_Monitoring_Alarm_Status_Alarm_Pressure',
     'ECC_Monitoring_Alarm_Status_Alarm_Smoke',
     'ECC_Monitoring_Alarm_Status_Alarm_Spare',
     'ECC_Monitoring_Alarm_Status_Alarm_Temperature',
     'ECC_Monitoring_Alarm_Status_Alarm_WaterLeak',
     'ECC_Monitoring_Alarm_Status_Alarm_WaterPressure',
     'ECC_Monitoring_Alarm_Status_WarningFanTachymeter',
     'ECC_Monitoring_Alarm_Status_Warning_Temperature',
     'ECC_Monitoring_Chiller_CommunicationStatus',
     'ECC_Monitoring_Chiller_ECC_RegulationStatus',
     'ECC_Monitoring_Chiller_ECC_RegulationSwitchCode',
     'ECC_Monitoring_Chiller_ECC_RegulationSwitchString',
     'ECC_Monitoring_Chiller_ErrorCode',
     'ECC_Monitoring_Chiller_FSMState',
     'ECC_Monitoring_Chiller_GeneralStatus',
     'ECC_Monitoring_Chiller_HP_LP_Pressure',
     'ECC_Monitoring_Chiller_Heating_Cooling_Countdown',
     'ECC_Monitoring_Chiller_RelayStatus',
     'ECC_Monitoring_Chiller_TemperatureAmbiant',
     'ECC_Monitoring_Chiller_TemperatureEvaporatorWater',
     'ECC_Monitoring_Chiller_TemperatureTankWater',
     'ECC_Monitoring_CommissioningMode',
     'ECC_Monitoring_CoolingValve_CoolingRegulationStatus',
     'ECC_Monitoring_CoolingValve_CoolingValveError',
     'ECC_Monitoring_CoolingValve_CoolingValveStatus',
     'ECC_Monitoring_Debug_ECC_ECC_Program_Version',
     'ECC_Monitoring_ECC_Error_ErrorDescription',
     'ECC_Monitoring_ECC_Error_ErrorNumber',
     'ECC_Monitoring_ECC_Error_ErrorResolution',
     'ECC_Monitoring_Front_fans_FanTachymeterError_',
     'ECC_Monitoring_Front_fans_FanTachymeter_',
     'ECC_Monitoring_Front_fans_GeneralStatus',
     'ECC_Monitoring_IntelligentRelay_Current',
     'ECC_Monitoring_IntelligentRelay_Status',
     'ECC_Monitoring_IntelligentRelay_StatusMonitoring',
     'ECC_Monitoring_IntelligentRelay_Voltage',
     'ECC_Monitoring_LEDPositions_GeneralStatus',
     'ECC_Monitoring_LEDPositions_Led_',
     'ECC_Monitoring_PDB_ActiveEnergy400V',
     'ECC_Monitoring_PDB_ApparentEnergy400V',
     'ECC_Monitoring_PDB_Cosinus400V',
     'ECC_Monitoring_PDB_CurrentSensors_CurrentSupply230V',
     'ECC_Monitoring_PDB_CurrentSensors_CurrentSupply400V_L',
     'ECC_Monitoring_PDB_Frequency400V',
     'ECC_Monitoring_PDB_PDBStatus_Led_Control',
     'ECC_Monitoring_PDB_PDBStatus_OF_MOTOR_400V',
     'ECC_Monitoring_PDB_PDBStatus_OF_MOTOR_AUX_400V',
     'ECC_Monitoring_PDB_PDBStatus_OF_MOTOR_AUX_SAI',
     'ECC_Monitoring_PDB_PDBStatus_OF_MOTOR_SAI',
     'ECC_Monitoring_PDB_PDBStatus_SD_MOTOR_400V',
     'ECC_Monitoring_PDB_PDBStatus_SD_MOTOR_SAI',
     'ECC_Monitoring_PDB_PDBStatus_StateBreaker',
     'ECC_Monitoring_PDB_PDBStatus_StateEmergencyStop',
     'ECC_Monitoring_PDB_PDBStatus_SwitchStatus_General230V',
     'ECC_Monitoring_PDB_PDBStatus_SwitchStatus_General400V',
     'ECC_Monitoring_PDB_PDBStatus_SwitchStatus_fanFront',
     'ECC_Monitoring_PDB_PDBStatus_SwitchStatus_fanRear',
     'ECC_Monitoring_PDB_PDBStatus_SwitchStatus_line400V',
     'ECC_Monitoring_PDB_PDBStatus_SwitchStatus_shutter',
     'ECC_Monitoring_PDB_PDBStatus_SwitchStatus_switch1',
     'ECC_Monitoring_PDB_PDBStatus_SwitchStatus_switch2',
     'ECC_Monitoring_PDB_PDBStatus_TriggerPowerSupply',
     'ECC_Monitoring_PDB_PhaseToPhase400VSensors_PhaseToPhase400V_L',
     'ECC_Monitoring_PDB_Power_ActivePower400V_L',
     'ECC_Monitoring_PDB_Power_ActivePowerUPS',
     'ECC_Monitoring_PDB_Power_ApparentPower400V_L',
     'ECC_Monitoring_PDB_Power_ApparentPowerUPS',
     'ECC_Monitoring_PDB_Power_PowerFactorUPS',
     'ECC_Monitoring_PDB_Power_PowerFactor_L',
     'ECC_Monitoring_PDB_Power_ReactiveCapacitivePowerUPS',
     'ECC_Monitoring_PDB_Power_ReactiveInductivePowerUPS',
     'ECC_Monitoring_PDB_Power_ReactivePower400V_L',
     'ECC_Monitoring_PDB_Power_ReactivePowerUPS',
     'ECC_Monitoring_PDB_Temperature',
     'ECC_Monitoring_PDB_VoltageSensors_VoltageSupply230V',
     'ECC_Monitoring_PDB_VoltageSensors_VoltageSupply400V_L',
     'ECC_Monitoring_PSB_CurrentSupply24VPSB',
     'ECC_Monitoring_PSB_PowerSupplyPSB1_',
     'ECC_Monitoring_PSB_PowerSupplyPSB2_',
     'ECC_Monitoring_Rear_fans_GeneralStatus',
     'ECC_Monitoring_Sensors_AirDifferentialPressureSensors_AirDifferentialPressureSensor',
     'ECC_Monitoring_Sensors_AirDifferentialPressureSensors_AirDifferentialPresureSensor',
     'ECC_Monitoring_Sensors_Doors_BackDoorsOpen',
     'ECC_Monitoring_Sensors_Doors_BackDoorsSensor',
     'ECC_Monitoring_Sensors_Doors_FrontDoorsOpen',
     'ECC_Monitoring_Sensors_Flowmeters_FlowmeterSensor',
     'ECC_Monitoring_Sensors_HumiditySensors_HumiditySensor',
     'ECC_Monitoring_Sensors_HumiditySensors_TempSensor',
     'ECC_Monitoring_Sensors_LightSensors_Light_',
     'ECC_Monitoring_Sensors_SmokeSensors_SmokeSensor',
     'ECC_Monitoring_Sensors_TemperatureSensors_TemperatureSensor_',
     'ECC_Monitoring_Sensors_WaterLeakSensors_WaterLeakSensor',
     'ECC_Monitoring_Sensors_WaterPressureSensors_WaterPressureSensor_',
     'ECC_Monitoring_Sensors_WaterPressureSensors_WaterPresureSensor_',
     'ECC_Monitoring_Shutter_Down_Contactor',
     'ECC_Monitoring_Shutter_Error',
     'ECC_Monitoring_Shutter_ErrorInfo',
     'ECC_Monitoring_Shutter_GeneralStatus',
     'ECC_Monitoring_Shutter_KeyStatus',
     'ECC_Monitoring_Shutter_PLC_Shutter_PLC_AngularSensor',
     'ECC_Monitoring_Shutter_PLC_Shutter_PLC_CloseButton',
     'ECC_Monitoring_Shutter_PLC_Shutter_PLC_CommunicationStatus',
     'ECC_Monitoring_Shutter_PLC_Shutter_PLC_EmergencyButton',
     'ECC_Monitoring_Shutter_PLC_Shutter_PLC_ErrorType',
     'ECC_Monitoring_Shutter_PLC_Shutter_PLC_OpenButton',
     'ECC_Monitoring_Shutter_PLC_Shutter_PLC_Reserved',
     'ECC_Monitoring_Shutter_PLC_Shutter_PLC_SelectAutoManual',
     'ECC_Monitoring_Shutter_PLC_Shutter_PLC_Status',
     'ECC_Monitoring_Shutter_PLC_Shutter_PLC_WireSensor',
     'ECC_Monitoring_Shutter_Up_Contactor',
     'ECC_Monitoring_Spares_Analog_A0_',
     'ECC_Monitoring_Spares_Analog_AI_',
     'ECC_Monitoring_Spares_Digital_D0_',
     'ECC_Monitoring_Spares_Digital_DI_',
     'ECC_Monitoring_Spares_Heater',
     'ECC_Monitoring_Transition_Countdown',
     'ECC_Monitoring_Transition_Information',
     'ECC_Monitoring_WhiteTarget_Horizontal_BottomLeft',
     'ECC_Monitoring_WhiteTarget_Horizontal_BottomRight',
     'ECC_Monitoring_WhiteTarget_Horizontal_HorizontalEncoder',
     'ECC_Monitoring_WhiteTarget_Horizontal_TopLeft',
     'ECC_Monitoring_WhiteTarget_Horizontal_TopRight',
     'ECC_Monitoring_WhiteTarget_Vertical_Bottom',
     'ECC_Monitoring_WhiteTarget_Vertical_Top',
     'ECC_Monitoring_WhiteTarget_Vertical_VerticalEncoder',
     'ECC__ControlLoopTimeStamp',
     'TIB_Alarm_AlarmVector',
     'TIB_Alarm_AlmostFull',
     'TIB_Alarm_BufferFull',
     'TIB_Alarm_PPSFailure',
     'TIB_Alarm_ReadError',
     'TIB_Alarm_Unlocked',
     'TIB_Alarm_WriteError',
     'TIB_ArmedDelayStereo',
     'TIB_BUSY_BusyBP',
     'TIB_BUSY_DisableBusy',
     'TIB_BUSY_ExtraDelayBusy',
     'TIB_BUSY_InternalBusy',
     'TIB_Clock_select',
     'TIB_CoincidenceWindow',
     'TIB_ConnectionStatus',
     'TIB_DACOptical_Neighbour',
     'TIB_DebugVector',
     'TIB_Delays_CompoundDelay',
     'TIB_Delays_Delay',
     'TIB_Delays_DelayLocal',
     'TIB_EventsInRun_BUSYRun',
     'TIB_EventsInRun_CalibrationRun',
     'TIB_EventsInRun_CameraRun',
     'TIB_EventsInRun_CollectedRun',
     'TIB_EventsInRun_In1Run',
     'TIB_EventsInRun_In2Run',
     'TIB_EventsInRun_In3Run',
     'TIB_EventsInRun_In4Run',
     'TIB_EventsInRun_LocalRun',
     'TIB_EventsInRun_PPSRun',
     'TIB_EventsInRun_PedestalRun',
     'TIB_EventsInRun_SlowControlRun',
     'TIB_EventsInRun_SoftrigRun',
     'TIB_EventsInRun_SpheRun',
     'TIB_EventsInRun_StereoRun',
     'TIB_ExternalDelay_ExternalDelayCalibration',
     'TIB_ExternalDelay_ExternalDelayLocal',
     'TIB_ExternalDelay_ExternalDelaySphe',
     'TIB_InputsEnable_Input',
     'TIB_InputsEnable_InputLocal',
     'TIB_InputsEnable_InputMask',
     'TIB_OF_delayMeasure_Launch_OF_measure',
     'TIB_OF_delayMeasure_OF_delay',
     'TIB_OF_delayMeasure_Passive_OF_resend',
     'TIB_Pedestal_AnalogPedestalEnable',
     'TIB_Pedestal_AnalogPedestalThreshold',
     'TIB_Pedestal_DigitalPedestalEnable',
     'TIB_Pedestal_DigitalPedestalSeed',
     'TIB_Pedestal_DigitalPedestal_config_Rate',
     'TIB_Pedestal_Fake_trig_enable',
     'TIB_Pedestal_PeriodicPedestalEnable',
     'TIB_Pedestal_PeriodicPedestalFrequency',
     'TIB_Rates_BUSYRate',
     'TIB_Rates_CalibrationRate',
     'TIB_Rates_CameraRate',
     'TIB_Rates_CollectedRate',
     'TIB_Rates_In1Rate',
     'TIB_Rates_In2Rate',
     'TIB_Rates_In3Rate',
     'TIB_Rates_In4Rate',
     'TIB_Rates_In5Rate',
     'TIB_Rates_In6Rate',
     'TIB_Rates_In7Rate',
     'TIB_Rates_In8Rate',
     'TIB_Rates_LocalRate',
     'TIB_Rates_PedestalRate',
     'TIB_Rates_SoftrigRate',
     'TIB_Rates_SpheRate',
     'TIB_Rates_StereoRate',
     'TIB_ReadState',
     'TIB_RedundantCables_RedundantCable',
     'TIB_StereoCondition',
     'TIB_TIB_TXclient_alive',
     'TIB_Temperature',
     'TIB_Throttler_DisableThrottler',
     'TIB_Throttler_MaxTriggers1ms',
     'TIB_Throttler_MaxTriggers50us',
     'TIB_TriggerMode_CalibrationEnable',
     'TIB_TriggerMode_ModeMask',
     'TIB_TriggerMode_MonoEnable',
     'TIB_TriggerMode_PedestalEnable',
     'TIB_TriggerMode_SlowControlEnable',
     'TIB_TriggerMode_SoftwareTrigEnable',
     'TIB_TriggerMode_SpheEnable',
     'TIB_TriggerMode_StereoEnable',
     'TIB__ControlLoopTimeStamp',
     'exports_FSM_error_error_message',
     'exports_FSM_state',
     'exports__ControlLoopTimeStamp',
     'exports_actions_calibrations_external_delay_end_time',
     'exports_actions_calibrations_external_delay_start_time',
     'exports_actions_calibrations_external_delay_status',
     'exports_actions_calibrations_external_delay_values',
     'exports_actions_calibrations_external_delay_xtra_information',
     'exports_actions_calibrations_external_gain_end_time',
     'exports_actions_calibrations_external_gain_start_time',
     'exports_actions_calibrations_external_gain_status',
     'exports_actions_calibrations_external_gain_values',
     'exports_actions_calibrations_external_gain_xtra_information',
     'exports_actions_calibrations_internal_delay_end_time',
     'exports_actions_calibrations_internal_delay_start_time',
     'exports_actions_calibrations_internal_delay_status',
     'exports_actions_calibrations_internal_delay_values',
     'exports_actions_calibrations_internal_delay_xtra_information',
     'exports_actions_calibrations_internal_gain_end_time',
     'exports_actions_calibrations_internal_gain_start_time',
     'exports_actions_calibrations_internal_gain_status',
     'exports_actions_calibrations_internal_gain_values',
     'exports_actions_calibrations_internal_gain_xtra_information',
     'exports_actions_calibrations_pixel_DTN0',
     'exports_actions_calibrations_pixel_DTl0',
     'exports_actions_calibrations_pixels_DTL0',
     'exports_actions_calibrations_pixels_DTN',
     'exports_actions_scans_scan_ipr_begin',
     'exports_actions_scans_scan_ipr_end',
     'exports_actions_scans_scan_ipr_end_time',
     'exports_actions_scans_scan_ipr_start_time',
     'exports_actions_scans_scan_ipr_status',
     'exports_actions_scans_scan_ipr_steps',
     'exports_actions_scans_scan_ipr_values_values',
     'exports_actions_scans_scan_l1_begin',
     'exports_actions_scans_scan_l1_end',
     'exports_actions_scans_scan_l1_end_time',
     'exports_actions_scans_scan_l1_start_time',
     'exports_actions_scans_scan_l1_status',
     'exports_actions_scans_scan_l1_steps',
     'exports_actions_scans_scan_l1_values_values',
     'exports_monitoring_clusco_busy_state',
     'exports_monitoring_clusco_central_bp',
     'exports_monitoring_clusco_date_built',
     'exports_monitoring_clusco_error',
     'exports_monitoring_clusco_hv_on',
     'exports_monitoring_clusco_l0_hot',
     'exports_monitoring_clusco_l0_rate_control',
     'exports_monitoring_clusco_l0_rate_max',
     'exports_monitoring_clusco_l1_rate_control',
     'exports_monitoring_clusco_l1_rate_max',
     'exports_monitoring_clusco_l1_rate_target',
     'exports_monitoring_clusco_last_report_msecond',
     'exports_monitoring_clusco_last_report_second',
     'exports_monitoring_clusco_major_ver',
     'exports_monitoring_clusco_major_version',
     'exports_monitoring_clusco_mean_dc',
     'exports_monitoring_clusco_mean_dc_healthy',
     'exports_monitoring_clusco_minor_ver',
     'exports_monitoring_clusco_minor_version',
     'exports_monitoring_clusco_monitoring_sleep',
     'exports_monitoring_clusco_nb_hv_reduced',
     'exports_monitoring_clusco_read_once_msecond',
     'exports_monitoring_clusco_read_once_second',
     'exports_monitoring_clusco_read_rarely_msecond',
     'exports_monitoring_clusco_read_rarely_second',
     'exports_monitoring_clusco_sub_ver',
     'exports_monitoring_clusco_sub_version',
     'exports_monitoring_clusco_time_built',
     'exports_monitoring_clusco_zenith',
     'exports_monitoring_hardware_values_cluster_backplane_firmware',
     'exports_monitoring_hardware_values_cluster_backplane_flag',
     'exports_monitoring_hardware_values_cluster_backplane_reg65',
     'exports_monitoring_hardware_values_cluster_backplane_scalar',
     'exports_monitoring_hardware_values_cluster_backplane_tdc_delta',
     'exports_monitoring_hardware_values_cluster_backplane_temperature',
     'exports_monitoring_hardware_values_cluster_bp_scalar',
     'exports_monitoring_hardware_values_cluster_bp_tdc_delta',
     'exports_monitoring_hardware_values_cluster_bp_temperature',
     'exports_monitoring_hardware_values_cluster_busy',
     'exports_monitoring_hardware_values_cluster_dragon_busy',
     'exports_monitoring_hardware_values_cluster_dragon_drs4_humidity',
     'exports_monitoring_hardware_values_cluster_dragon_drs4_temperature',
     'exports_monitoring_hardware_values_cluster_dragon_drs_cascade_channels',
     'exports_monitoring_hardware_values_cluster_dragon_drs_mode',
     'exports_monitoring_hardware_values_cluster_dragon_drs_offset',
     'exports_monitoring_hardware_values_cluster_dragon_drs_read_depth',
     'exports_monitoring_hardware_values_cluster_dragon_drs_sampling_frequency',
     'exports_monitoring_hardware_values_cluster_dragon_drs_trigger_delay',
     'exports_monitoring_hardware_values_cluster_dragon_drs_trigger_selection',
     'exports_monitoring_hardware_values_cluster_dragon_firmware',
     'exports_monitoring_hardware_values_cluster_dragon_flag',
     'exports_monitoring_hardware_values_cluster_dragon_l0_rate_window',
     'exports_monitoring_hardware_values_cluster_dragon_l1_rate_window',
     'exports_monitoring_hardware_values_cluster_dragon_mac_address',
     'exports_monitoring_hardware_values_cluster_dragon_reg_temperature',
     'exports_monitoring_hardware_values_cluster_dragon_six_v',
     'exports_monitoring_hardware_values_cluster_dragon_tp_injection',
     'exports_monitoring_hardware_values_cluster_dragon_tp_rate',
     'exports_monitoring_hardware_values_cluster_enabled',
     'exports_monitoring_hardware_values_cluster_error',
     'exports_monitoring_hardware_values_cluster_l0_majority',
     'exports_monitoring_hardware_values_cluster_l0_sate',
     'exports_monitoring_hardware_values_cluster_l0_sum',
     'exports_monitoring_hardware_values_cluster_l1_adder',
     'exports_monitoring_hardware_values_cluster_l1_dac_threshold_default',
     'exports_monitoring_hardware_values_cluster_l1_dac_threshold_set',
     'exports_monitoring_hardware_values_cluster_l1_extern_rate',
     'exports_monitoring_hardware_values_cluster_l1_rate',
     'exports_monitoring_hardware_values_cluster_l1_rate_low',
     'exports_monitoring_hardware_values_cluster_l1_state',
     'exports_monitoring_hardware_values_cluster_majority_enabled',
     'exports_monitoring_hardware_values_cluster_number',
     'exports_monitoring_hardware_values_cluster_port',
     'exports_monitoring_hardware_values_cluster_scb_flag',
     'exports_monitoring_hardware_values_cluster_scb_humidity',
     'exports_monitoring_hardware_values_cluster_scb_hw_version',
     'exports_monitoring_hardware_values_cluster_scb_id_code',
     'exports_monitoring_hardware_values_cluster_scb_pmask',
     'exports_monitoring_hardware_values_cluster_scb_pmt_current',
     'exports_monitoring_hardware_values_cluster_scb_sw_version',
     'exports_monitoring_hardware_values_cluster_scb_temperature',
     'exports_monitoring_hardware_values_cluster_scb_testpulse_enabled',
     'exports_monitoring_hardware_values_cluster_scb_uid',
     'exports_monitoring_hardware_values_cluster_state',
     'exports_monitoring_hardware_values_cluster_sum_enabled',
     'exports_monitoring_hardware_values_cluster_sw_version',
     'exports_monitoring_hardware_values_cluster_tp_rate',
     'exports_monitoring_hardware_values_pixel_AN_current',
     'exports_monitoring_hardware_values_pixel_clipping_bias',
     'exports_monitoring_hardware_values_pixel_clipping_sel',
     'exports_monitoring_hardware_values_pixel_delay',
     'exports_monitoring_hardware_values_pixel_dt',
     'exports_monitoring_hardware_values_pixel_enabled',
     'exports_monitoring_hardware_values_pixel_error',
     'exports_monitoring_hardware_values_pixel_gain',
     'exports_monitoring_hardware_values_pixel_l0_asic_main_register',
     'exports_monitoring_hardware_values_pixel_l0_clipping_bias',
     'exports_monitoring_hardware_values_pixel_l0_clipping_sel',
     'exports_monitoring_hardware_values_pixel_l0_delay',
     'exports_monitoring_hardware_values_pixel_l0_dt',
     'exports_monitoring_hardware_values_pixel_l0_gain',
     'exports_monitoring_hardware_values_pixel_l0_ipr',
     'exports_monitoring_hardware_values_pixel_l0_on',
     'exports_monitoring_hardware_values_pixel_l0_rate',
     'exports_monitoring_hardware_values_pixel_l0_threshold_register',
     'exports_monitoring_hardware_values_pixel_pixel_error',
     'exports_monitoring_hardware_values_pixel_scb_amplifier_id_code',
     'exports_monitoring_hardware_values_pixel_scb_an_current',
     'exports_monitoring_hardware_values_pixel_scb_hotcold',
     'exports_monitoring_hardware_values_pixel_scb_hv_default',
     'exports_monitoring_hardware_values_pixel_scb_hv_monitored',
     'exports_monitoring_hardware_values_pixel_scb_hv_set',
     'exports_monitoring_hardware_values_pixel_scb_pcode',
     'exports_monitoring_hardware_values_pixel_scb_pixel_temperature',
     'exports_monitoring_hardware_values_pixel_scb_temperature',
     'exports_monitoring_hardware_values_pixel_scb_tp_boost',
     'exports_monitoring_hardware_values_pixel_scb_tp_gain',
     'exports_monitoring_hardware_values_pixel_tp_boost',
     'exports_monitoring_number_of_cluster',
     'exports_monitoring_number_of_clusters',
     'exports_monitoring_state',
     'exports_monitoring_version']


    dict_tcu_property_bytes = {'CalibrationBox_BG_InterCalibration_Mean': 0,
     'CalibrationBox_DewPoint': 0,
     'CalibrationBox_Error_BG_InterCalibration_Mean': 0,
     'CalibrationBox_Error_InterCalibration_Mean': 0,
     'CalibrationBox_FSM_state': 0,
     'CalibrationBox_FSM_transition': 0,
     'CalibrationBox_Humidity': 0,
     'CalibrationBox_InterCalibration_Mean': 0,
     'CalibrationBox_LaserErrorCode': 0,
     'CalibrationBox_LaserInfoCode': 0,
     'CalibrationBox_LaserStatus': 0,
     'CalibrationBox_LaserTrigParameters': 0,
     'CalibrationBox_PedStatus': 0,
     'CalibrationBox_PedTrigParameters': 0,
     'CalibrationBox_PowerStatus': 0,
     'CalibrationBox_PowerStatusLR': 0,
     'CalibrationBox_Pressure': 0,
     'CalibrationBox_Temperature': 0,
     'CalibrationBox_WheelPosition': 0,
     'Calibration_CalibrationBox_Humidity': 0,
     'Calibration_CalibrationBox_LaserErrorCode': 0,
     'Calibration_CalibrationBox_LaserInfoCode': 0,
     'Calibration_CalibrationBox_LaserStatus': 0,
     'Calibration_CalibrationBox_LaserTrigParameters': 0,
     'Calibration_CalibrationBox_PowerStatus': 0,
     'Calibration_CalibrationBox_Pressure': 0,
     'Calibration_CalibrationBox_Temperature': 0,
     'Calibration_CalibrationBox_WheelPosition': 0,
     'CameraControl_CBOXControl_state': 121,
     'CameraControl_FSM_is_transit': 118,
     'CameraControl_FSM_is_warm_up': 118,
     'CameraControl_FSM_previous_state': 121,
     'CameraControl_FSM_state': 121,
     'CameraControl_InstrumentProtection_mode': 127,
     'CameraControl_InstrumentProtection_status': 121,
     'CameraControl_MessageAdviser_last_message': 0,
     'CameraControl_ModulesAvailable_CBOX_valid_connection': 118,
     'CameraControl_ModulesAvailable_CLUS_valid_connection': 118,
     'CameraControl_ModulesAvailable_DAQ_valid_connection': 118,
     'CameraControl_ModulesAvailable_ECC_valid_connection': 118,
     'CameraControl_ModulesAvailable_Sphe_valid_connection': 0,
     'CameraControl_ModulesAvailable_TIB_valid_connection': 118,
     'CameraControl_ModulesAvailable_UCTS_valid_connection': 118,
     'CameraControl_ModulesStatus_CLUSCO': 121,
     'CameraControl_ModulesStatus_CS': 121,
     'CameraControl_ModulesStatus_DAQ': 121,
     'CameraControl_ModulesStatus_ECC': 121,
     'CameraControl_ModulesStatus_SIS': 121,
     'CameraControl_ModulesStatus_TIB': 121,
     'CameraControl_ModulesStatus_UCTS': 121,
     'CameraControl_RunUtils_is_test': 118,
     'CameraControl_RunUtils_run_number': 121,
     'CameraControl_UserAdviser_message': 122,
     'CameraControl__ControlLoopTimeStamp': 0,
     'CameraControl_heartbeat_caco_timestamp': 121,
     'CameraControl_heartbeat_enabled': 118,
     'CameraControl_heartbeat_time_limit': 0,
     'CameraControl_heartbeat_times_failed': 0,
     'CameraControl_information_MessageAdviser_last_message': 179,
     'CameraControl_information_error_state': 121,
     'Camera_CalibrationBox_BG_InterCalibration_Mean': 125,
     'Camera_CalibrationBox_DewPoint': 125,
     'Camera_CalibrationBox_Error_BG_InterCalibration_Mean': 125,
     'Camera_CalibrationBox_Error_InterCalibration_Mean': 125,
     'Camera_CalibrationBox_Humidity': 189,
     'Camera_CalibrationBox_InterCalibration_Mean': 125,
     'Camera_CalibrationBox_LaserErrorCode': 122,
     'Camera_CalibrationBox_LaserInfoCode': 122,
     'Camera_CalibrationBox_LaserStatus': 121,
     'Camera_CalibrationBox_LaserTrigParameters': 136,
     'Camera_CalibrationBox_PedRndTrigParameter': 125,
     'Camera_CalibrationBox_PedStatus': 121,
     'Camera_CalibrationBox_PedTrigParameters': 155,
     'Camera_CalibrationBox_PowerStatus': 118,
     'Camera_CalibrationBox_PowerStatusLR': 118,
     'Camera_CalibrationBox_Pressure': 125,
     'Camera_CalibrationBox_Temperature': 157,
     'Camera_CalibrationBox_WheelPosition': 144,
     'Camera_UCTS_ConfigurationParameters_CDTS_MAC_Address': 0,
     'Camera_UCTS_ConfigurationParameters_OPCUA_server_IP_Address': 0,
     'Camera_UCTS_ConfigurationParameters_UCTS_IP_Address': 0,
     'Camera_UCTS_Configuration_UctsIpAddr': 130,
     'Camera_UCTS_FSM_state': 0,
     'Camera_UCTS_FSM_transition': 0,
     'Camera_UCTS_HardwareConfig_state': 0,
     'Camera_UCTS_SNMPParameters_SNMP_Port_Link_Status': 0,
     'Camera_UCTS_SNMPParameters_SNMP_Temperature': 0,
     'Camera_UCTS_SNMPParameters_SNMP_Time_TAI': 0,
     'Camera_UCTS_SNMPParameters_SNMP_Up_Time': 0,
     'Camera_UCTS_SNMPParameters_SNMP_wrpc_Sw_Version': 0,
     'Camera_UCTS_SNMP_BusyCount': 121,
     'Camera_UCTS_SNMP_DstIpAddr': 168,
     'Camera_UCTS_SNMP_DstMacAddr': 122,
     'Camera_UCTS_SNMP_DstPort': 121,
     'Camera_UCTS_SNMP_EventCount': 121,
     'Camera_UCTS_SNMP_PortLinkStatus': 124,
     'Camera_UCTS_SNMP_Status': 149,
     'Camera_UCTS_SNMP_Temperature': 221,
     'Camera_UCTS_SNMP_Throttle': 121,
     'Camera_UCTS_SNMP_TimeTAI': 0,
     'Camera_UCTS_SNMP_UpTime': 249,
     'Camera_UCTS_SNMP_WrpcSwVersion': 122,
     'Camera__ControlLoopTimeStamp': 0,
     'Camera__Enable_Heart_Beat': 0,
     'Camera__Error_Heart_Beat': 0,
     'Camera__Heart_Beat': 0,
     'ECC_FSM_state': 121,
     'ECC_FSM_transition': 121,
     'ECC_Monitoring_AirValve_AirRegulationStatus': 118,
     'ECC_Monitoring_AirValve_AirValveError': 118,
     'ECC_Monitoring_AirValve_AirValveStatus': 118,
     'ECC_Monitoring_Alarm_Status_Alarm_Back_Door': 118,
     'ECC_Monitoring_Alarm_Status_Alarm_Caco_HeartBeat': 118,
     'ECC_Monitoring_Alarm_Status_Alarm_ChillerHeating': 118,
     'ECC_Monitoring_Alarm_Status_Alarm_Current_24V_PSU1': 118,
     'ECC_Monitoring_Alarm_Status_Alarm_Current_24V_PSU2': 118,
     'ECC_Monitoring_Alarm_Status_Alarm_Flowmeter': 118,
     'ECC_Monitoring_Alarm_Status_Alarm_Front_Door': 118,
     'ECC_Monitoring_Alarm_Status_Alarm_General_current': 118,
     'ECC_Monitoring_Alarm_Status_Alarm_Humidity': 118,
     'ECC_Monitoring_Alarm_Status_Alarm_IR': 118,
     'ECC_Monitoring_Alarm_Status_Alarm_Light': 118,
     'ECC_Monitoring_Alarm_Status_Alarm_PDB': 118,
     'ECC_Monitoring_Alarm_Status_Alarm_Pressure': 118,
     'ECC_Monitoring_Alarm_Status_Alarm_Smoke': 118,
     'ECC_Monitoring_Alarm_Status_Alarm_Spare': 136,
     'ECC_Monitoring_Alarm_Status_Alarm_Temperature': 118,
     'ECC_Monitoring_Alarm_Status_Alarm_WaterLeak': 118,
     'ECC_Monitoring_Alarm_Status_Alarm_WaterPressure': 118,
     'ECC_Monitoring_Alarm_Status_WarningFanTachymeter': 118,
     'ECC_Monitoring_Alarm_Status_Warning_Temperature': 118,
     'ECC_Monitoring_Chiller_CommunicationStatus': 121,
     'ECC_Monitoring_Chiller_ECC_RegulationStatus': 118,
     'ECC_Monitoring_Chiller_ECC_RegulationSwitchCode': 121,
     'ECC_Monitoring_Chiller_ECC_RegulationSwitchString': 157,
     'ECC_Monitoring_Chiller_ErrorCode': 123,
     'ECC_Monitoring_Chiller_FSMState': 121,
     'ECC_Monitoring_Chiller_GeneralStatus': 123,
     'ECC_Monitoring_Chiller_HP_LP_Pressure': 121,
     'ECC_Monitoring_Chiller_Heating_Cooling_Countdown': 121,
     'ECC_Monitoring_Chiller_RelayStatus': 121,
     'ECC_Monitoring_Chiller_TemperatureAmbiant': 125,
     'ECC_Monitoring_Chiller_TemperatureEvaporatorWater': 125,
     'ECC_Monitoring_Chiller_TemperatureTankWater': 125,
     'ECC_Monitoring_CommissioningMode': 0,
     'ECC_Monitoring_CoolingValve_CoolingRegulationStatus': 118,
     'ECC_Monitoring_CoolingValve_CoolingValveError': 118,
     'ECC_Monitoring_CoolingValve_CoolingValveStatus': 121,
     'ECC_Monitoring_Debug_ECC_ECC_Program_Version': 133,
     'ECC_Monitoring_ECC_Error_ErrorDescription': 123,
     'ECC_Monitoring_ECC_Error_ErrorNumber': 121,
     'ECC_Monitoring_ECC_Error_ErrorResolution': 123,
     'ECC_Monitoring_Front_fans_FanTachymeterError_': 264,
     'ECC_Monitoring_Front_fans_FanTachymeter_': 8267,
     'ECC_Monitoring_Front_fans_GeneralStatus': 121,
     'ECC_Monitoring_IntelligentRelay_Current': 210,
     'ECC_Monitoring_IntelligentRelay_Status': 178,
     'ECC_Monitoring_IntelligentRelay_StatusMonitoring': 178,
     'ECC_Monitoring_IntelligentRelay_Voltage': 210,
     'ECC_Monitoring_LEDPositions_GeneralStatus': 118,
     'ECC_Monitoring_LEDPositions_Led_': 240,
     'ECC_Monitoring_PDB_ActiveEnergy400V': 125,
     'ECC_Monitoring_PDB_ApparentEnergy400V': 125,
     'ECC_Monitoring_PDB_Cosinus400V': 578,
     'ECC_Monitoring_PDB_CurrentSensors_CurrentSupply230V': 125,
     'ECC_Monitoring_PDB_CurrentSensors_CurrentSupply400V_L': 1343,
     'ECC_Monitoring_PDB_Frequency400V': 125,
     'ECC_Monitoring_PDB_PDBStatus_Led_Control': 118,
     'ECC_Monitoring_PDB_PDBStatus_OF_MOTOR_400V': 118,
     'ECC_Monitoring_PDB_PDBStatus_OF_MOTOR_AUX_400V': 118,
     'ECC_Monitoring_PDB_PDBStatus_OF_MOTOR_AUX_SAI': 118,
     'ECC_Monitoring_PDB_PDBStatus_OF_MOTOR_SAI': 118,
     'ECC_Monitoring_PDB_PDBStatus_SD_MOTOR_400V': 118,
     'ECC_Monitoring_PDB_PDBStatus_SD_MOTOR_SAI': 118,
     'ECC_Monitoring_PDB_PDBStatus_StateBreaker': 118,
     'ECC_Monitoring_PDB_PDBStatus_StateEmergencyStop': 118,
     'ECC_Monitoring_PDB_PDBStatus_SwitchStatus_General230V': 118,
     'ECC_Monitoring_PDB_PDBStatus_SwitchStatus_General400V': 118,
     'ECC_Monitoring_PDB_PDBStatus_SwitchStatus_fanFront': 118,
     'ECC_Monitoring_PDB_PDBStatus_SwitchStatus_fanRear': 118,
     'ECC_Monitoring_PDB_PDBStatus_SwitchStatus_line400V': 118,
     'ECC_Monitoring_PDB_PDBStatus_SwitchStatus_shutter': 118,
     'ECC_Monitoring_PDB_PDBStatus_SwitchStatus_switch1': 118,
     'ECC_Monitoring_PDB_PDBStatus_SwitchStatus_switch2': 118,
     'ECC_Monitoring_PDB_PDBStatus_TriggerPowerSupply': 118,
     'ECC_Monitoring_PDB_PhaseToPhase400VSensors_PhaseToPhase400V_L': 776,
     'ECC_Monitoring_PDB_Power_ActivePower400V_L': 902,
     'ECC_Monitoring_PDB_Power_ActivePowerUPS': 189,
     'ECC_Monitoring_PDB_Power_ApparentPower400V_L': 1343,
     'ECC_Monitoring_PDB_Power_ApparentPowerUPS': 189,
     'ECC_Monitoring_PDB_Power_PowerFactorUPS': 253,
     'ECC_Monitoring_PDB_Power_PowerFactor_L': 902,
     'ECC_Monitoring_PDB_Power_ReactiveCapacitivePowerUPS': 381,
     'ECC_Monitoring_PDB_Power_ReactiveInductivePowerUPS': 125,
     'ECC_Monitoring_PDB_Power_ReactivePower400V_L': 902,
     'ECC_Monitoring_PDB_Power_ReactivePowerUPS': 381,
     'ECC_Monitoring_PDB_Temperature': 125,
     'ECC_Monitoring_PDB_VoltageSensors_VoltageSupply230V': 317,
     'ECC_Monitoring_PDB_VoltageSensors_VoltageSupply400V_L': 1280,
     'ECC_Monitoring_PSB_CurrentSupply24VPSB': 144,
     'ECC_Monitoring_PSB_PowerSupplyPSB1_': 150,
     'ECC_Monitoring_PSB_PowerSupplyPSB2_': 150,
     'ECC_Monitoring_Rear_fans_GeneralStatus': 0,
     'ECC_Monitoring_Sensors_AirDifferentialPressureSensors_AirDifferentialPressureSensor': 125,
     'ECC_Monitoring_Sensors_AirDifferentialPressureSensors_AirDifferentialPresureSensor': 0,
     'ECC_Monitoring_Sensors_Doors_BackDoorsOpen': 118,
     'ECC_Monitoring_Sensors_Doors_BackDoorsSensor': 136,
     'ECC_Monitoring_Sensors_Doors_FrontDoorsOpen': 118,
     'ECC_Monitoring_Sensors_Flowmeters_FlowmeterSensor': 125,
     'ECC_Monitoring_Sensors_HumiditySensors_HumiditySensor': 125,
     'ECC_Monitoring_Sensors_HumiditySensors_TempSensor': 125,
     'ECC_Monitoring_Sensors_LightSensors_Light_': 166,
     'ECC_Monitoring_Sensors_SmokeSensors_SmokeSensor': 118,
     'ECC_Monitoring_Sensors_TemperatureSensors_TemperatureSensor_': 4111,
     'ECC_Monitoring_Sensors_WaterLeakSensors_WaterLeakSensor': 118,
     'ECC_Monitoring_Sensors_WaterPressureSensors_WaterPressureSensor_': 552,
     'ECC_Monitoring_Sensors_WaterPressureSensors_WaterPresureSensor_': 0,
     'ECC_Monitoring_Shutter_Down_Contactor': 136,
     'ECC_Monitoring_Shutter_Error': 121,
     'ECC_Monitoring_Shutter_ErrorInfo': 122,
     'ECC_Monitoring_Shutter_GeneralStatus': 121,
     'ECC_Monitoring_Shutter_KeyStatus': 118,
     'ECC_Monitoring_Shutter_PLC_Shutter_PLC_AngularSensor': 125,
     'ECC_Monitoring_Shutter_PLC_Shutter_PLC_CloseButton': 118,
     'ECC_Monitoring_Shutter_PLC_Shutter_PLC_CommunicationStatus': 121,
     'ECC_Monitoring_Shutter_PLC_Shutter_PLC_EmergencyButton': 118,
     'ECC_Monitoring_Shutter_PLC_Shutter_PLC_ErrorType': 121,
     'ECC_Monitoring_Shutter_PLC_Shutter_PLC_OpenButton': 118,
     'ECC_Monitoring_Shutter_PLC_Shutter_PLC_Reserved': 121,
     'ECC_Monitoring_Shutter_PLC_Shutter_PLC_SelectAutoManual': 118,
     'ECC_Monitoring_Shutter_PLC_Shutter_PLC_Status': 121,
     'ECC_Monitoring_Shutter_PLC_Shutter_PLC_WireSensor': 125,
     'ECC_Monitoring_Shutter_Up_Contactor': 136,
     'ECC_Monitoring_Spares_Analog_A0_': 256,
     'ECC_Monitoring_Spares_Analog_AI_': 352,
     'ECC_Monitoring_Spares_Digital_D0_': 171,
     'ECC_Monitoring_Spares_Digital_DI_': 344,
     'ECC_Monitoring_Spares_Heater': 136,
     'ECC_Monitoring_Transition_Countdown': 121,
     'ECC_Monitoring_Transition_Information': 136,
     'ECC_Monitoring_WhiteTarget_Horizontal_BottomLeft': 0,
     'ECC_Monitoring_WhiteTarget_Horizontal_BottomRight': 0,
     'ECC_Monitoring_WhiteTarget_Horizontal_HorizontalEncoder': 0,
     'ECC_Monitoring_WhiteTarget_Horizontal_TopLeft': 0,
     'ECC_Monitoring_WhiteTarget_Horizontal_TopRight': 0,
     'ECC_Monitoring_WhiteTarget_Vertical_Bottom': 0,
     'ECC_Monitoring_WhiteTarget_Vertical_Top': 0,
     'ECC_Monitoring_WhiteTarget_Vertical_VerticalEncoder': 0,
     'ECC__ControlLoopTimeStamp': 0,
     'TIB_Alarm_AlarmVector': 121,
     'TIB_Alarm_AlmostFull': 118,
     'TIB_Alarm_BufferFull': 118,
     'TIB_Alarm_PPSFailure': 118,
     'TIB_Alarm_ReadError': 118,
     'TIB_Alarm_Unlocked': 118,
     'TIB_Alarm_WriteError': 118,
     'TIB_ArmedDelayStereo': 0,
     'TIB_BUSY_BusyBP': 118,
     'TIB_BUSY_DisableBusy': 0,
     'TIB_BUSY_ExtraDelayBusy': 0,
     'TIB_BUSY_InternalBusy': 118,
     'TIB_Clock_select': 0,
     'TIB_CoincidenceWindow': 125,
     'TIB_ConnectionStatus': 118,
     'TIB_DACOptical_Neighbour': 188,
     'TIB_DebugVector': 121,
     'TIB_Delays_CompoundDelay': 0,
     'TIB_Delays_Delay': 166,
     'TIB_Delays_DelayLocal': 125,
     'TIB_EventsInRun_BUSYRun': 0,
     'TIB_EventsInRun_CalibrationRun': 0,
     'TIB_EventsInRun_CameraRun': 0,
     'TIB_EventsInRun_CollectedRun': 0,
     'TIB_EventsInRun_In1Run': 0,
     'TIB_EventsInRun_In2Run': 0,
     'TIB_EventsInRun_In3Run': 0,
     'TIB_EventsInRun_In4Run': 0,
     'TIB_EventsInRun_LocalRun': 0,
     'TIB_EventsInRun_PPSRun': 0,
     'TIB_EventsInRun_PedestalRun': 0,
     'TIB_EventsInRun_SlowControlRun': 0,
     'TIB_EventsInRun_SoftrigRun': 0,
     'TIB_EventsInRun_SpheRun': 0,
     'TIB_EventsInRun_StereoRun': 0,
     'TIB_ExternalDelay_ExternalDelayCalibration': 0,
     'TIB_ExternalDelay_ExternalDelayLocal': 0,
     'TIB_ExternalDelay_ExternalDelaySphe': 0,
     'TIB_InputsEnable_Input': 150,
     'TIB_InputsEnable_InputLocal': 118,
     'TIB_InputsEnable_InputMask': 121,
     'TIB_OF_delayMeasure_Launch_OF_measure': 0,
     'TIB_OF_delayMeasure_OF_delay': 0,
     'TIB_OF_delayMeasure_Passive_OF_resend': 0,
     'TIB_Pedestal_AnalogPedestalEnable': 118,
     'TIB_Pedestal_AnalogPedestalThreshold': 125,
     'TIB_Pedestal_DigitalPedestalEnable': 118,
     'TIB_Pedestal_DigitalPedestalSeed': 0,
     'TIB_Pedestal_DigitalPedestal_config_Rate': 121,
     'TIB_Pedestal_Fake_trig_enable': 118,
     'TIB_Pedestal_PeriodicPedestalEnable': 118,
     'TIB_Pedestal_PeriodicPedestalFrequency': 121,
     'TIB_Rates_BUSYRate': 125,
     'TIB_Rates_CalibrationRate': 125,
     'TIB_Rates_CameraRate': 125,
     'TIB_Rates_CollectedRate': 125,
     'TIB_Rates_In1Rate': 125,
     'TIB_Rates_In2Rate': 125,
     'TIB_Rates_In3Rate': 125,
     'TIB_Rates_In4Rate': 125,
     'TIB_Rates_In5Rate': 0,
     'TIB_Rates_In6Rate': 0,
     'TIB_Rates_In7Rate': 0,
     'TIB_Rates_In8Rate': 0,
     'TIB_Rates_LocalRate': 125,
     'TIB_Rates_PedestalRate': 125,
     'TIB_Rates_SoftrigRate': 125,
     'TIB_Rates_SpheRate': 221,
     'TIB_Rates_StereoRate': 125,
     'TIB_ReadState': 121,
     'TIB_RedundantCables_RedundantCable': 136,
     'TIB_StereoCondition': 0,
     'TIB_TIB_TXclient_alive': 118,
     'TIB_Temperature': 221,
     'TIB_Throttler_DisableThrottler': 118,
     'TIB_Throttler_MaxTriggers1ms': 121,
     'TIB_Throttler_MaxTriggers50us': 121,
     'TIB_TriggerMode_CalibrationEnable': 118,
     'TIB_TriggerMode_ModeMask': 121,
     'TIB_TriggerMode_MonoEnable': 118,
     'TIB_TriggerMode_PedestalEnable': 118,
     'TIB_TriggerMode_SlowControlEnable': 118,
     'TIB_TriggerMode_SoftwareTrigEnable': 118,
     'TIB_TriggerMode_SpheEnable': 118,
     'TIB_TriggerMode_StereoEnable': 118,
     'TIB__ControlLoopTimeStamp': 0,
     'exports_FSM_error_error_message': 0,
     'exports_FSM_state': 149,
     'exports__ControlLoopTimeStamp': 0,
     'exports_actions_calibrations_external_delay_end_time': 0,
     'exports_actions_calibrations_external_delay_start_time': 0,
     'exports_actions_calibrations_external_delay_status': 121,
     'exports_actions_calibrations_external_delay_values': 32402,
     'exports_actions_calibrations_external_delay_xtra_information': 124,
     'exports_actions_calibrations_external_gain_end_time': 0,
     'exports_actions_calibrations_external_gain_start_time': 0,
     'exports_actions_calibrations_external_gain_status': 121,
     'exports_actions_calibrations_external_gain_values': 9612,
     'exports_actions_calibrations_external_gain_xtra_information': 124,
     'exports_actions_calibrations_internal_delay_end_time': 0,
     'exports_actions_calibrations_internal_delay_start_time': 0,
     'exports_actions_calibrations_internal_delay_status': 121,
     'exports_actions_calibrations_internal_delay_values': 24982,
     'exports_actions_calibrations_internal_delay_xtra_information': 124,
     'exports_actions_calibrations_internal_gain_end_time': 0,
     'exports_actions_calibrations_internal_gain_start_time': 0,
     'exports_actions_calibrations_internal_gain_status': 121,
     'exports_actions_calibrations_internal_gain_values': 17562,
     'exports_actions_calibrations_internal_gain_xtra_information': 124,
     'exports_actions_calibrations_pixel_DTN0': 0,
     'exports_actions_calibrations_pixel_DTl0': 0,
     'exports_actions_calibrations_pixels_DTL0': 17562,
     'exports_actions_calibrations_pixels_DTN': 36112,
     'exports_actions_scans_scan_ipr_begin': 121,
     'exports_actions_scans_scan_ipr_end': 121,
     'exports_actions_scans_scan_ipr_end_time': 0,
     'exports_actions_scans_scan_ipr_start_time': 0,
     'exports_actions_scans_scan_ipr_status': 121,
     'exports_actions_scans_scan_ipr_steps': 121,
     'exports_actions_scans_scan_ipr_values_values': 0,
     'exports_actions_scans_scan_l1_begin': 121,
     'exports_actions_scans_scan_l1_end': 121,
     'exports_actions_scans_scan_l1_end_time': 0,
     'exports_actions_scans_scan_l1_start_time': 0,
     'exports_actions_scans_scan_l1_status': 121,
     'exports_actions_scans_scan_l1_steps': 121,
     'exports_actions_scans_scan_l1_values_values': 0,
     'exports_monitoring_clusco_busy_state': 149,
     'exports_monitoring_clusco_central_bp': 0,
     'exports_monitoring_clusco_date_built': 133,
     'exports_monitoring_clusco_error': 0,
     'exports_monitoring_clusco_hv_on': 118,
     'exports_monitoring_clusco_l0_hot': 121,
     'exports_monitoring_clusco_l0_rate_control': 118,
     'exports_monitoring_clusco_l0_rate_max': 121,
     'exports_monitoring_clusco_l1_rate_control': 118,
     'exports_monitoring_clusco_l1_rate_max': 121,
     'exports_monitoring_clusco_l1_rate_target': 0,
     'exports_monitoring_clusco_last_report_msecond': 121,
     'exports_monitoring_clusco_last_report_second': 125,
     'exports_monitoring_clusco_major_ver': 0,
     'exports_monitoring_clusco_major_version': 0,
     'exports_monitoring_clusco_mean_dc': 157,
     'exports_monitoring_clusco_mean_dc_healthy': 125,
     'exports_monitoring_clusco_minor_ver': 0,
     'exports_monitoring_clusco_minor_version': 0,
     'exports_monitoring_clusco_monitoring_sleep': 0,
     'exports_monitoring_clusco_nb_hv_reduced': 0,
     'exports_monitoring_clusco_read_once_msecond': 121,
     'exports_monitoring_clusco_read_once_second': 0,
     'exports_monitoring_clusco_read_rarely_msecond': 121,
     'exports_monitoring_clusco_read_rarely_second': 121,
     'exports_monitoring_clusco_sub_ver': 0,
     'exports_monitoring_clusco_sub_version': 0,
     'exports_monitoring_clusco_time_built': 130,
     'exports_monitoring_clusco_zenith': 125,
     'exports_monitoring_hardware_values_cluster_backplane_firmware': 0,
     'exports_monitoring_hardware_values_cluster_backplane_flag': 0,
     'exports_monitoring_hardware_values_cluster_backplane_reg65': 0,
     'exports_monitoring_hardware_values_cluster_backplane_scalar': 0,
     'exports_monitoring_hardware_values_cluster_backplane_tdc_delta': 0,
     'exports_monitoring_hardware_values_cluster_backplane_temperature': 0,
     'exports_monitoring_hardware_values_cluster_bp_scalar': 0,
     'exports_monitoring_hardware_values_cluster_bp_tdc_delta': 0,
     'exports_monitoring_hardware_values_cluster_bp_temperature': 0,
     'exports_monitoring_hardware_values_cluster_busy': 0,
     'exports_monitoring_hardware_values_cluster_dragon_busy': 4701,
     'exports_monitoring_hardware_values_cluster_dragon_drs4_humidity': 3457,
     'exports_monitoring_hardware_values_cluster_dragon_drs4_temperature': 0,
     'exports_monitoring_hardware_values_cluster_dragon_drs_cascade_channels': 0,
     'exports_monitoring_hardware_values_cluster_dragon_drs_mode': 2397,
     'exports_monitoring_hardware_values_cluster_dragon_drs_offset': 0,
     'exports_monitoring_hardware_values_cluster_dragon_drs_read_depth': 0,
     'exports_monitoring_hardware_values_cluster_dragon_drs_sampling_frequency': 0,
     'exports_monitoring_hardware_values_cluster_dragon_drs_trigger_delay': 2397,
     'exports_monitoring_hardware_values_cluster_dragon_drs_trigger_selection': 2397,
     'exports_monitoring_hardware_values_cluster_dragon_firmware': 2397,
     'exports_monitoring_hardware_values_cluster_dragon_flag': 2397,
     'exports_monitoring_hardware_values_cluster_dragon_l0_rate_window': 0,
     'exports_monitoring_hardware_values_cluster_dragon_l1_rate_window': 2397,
     'exports_monitoring_hardware_values_cluster_dragon_mac_address': 0,
     'exports_monitoring_hardware_values_cluster_dragon_reg_temperature': 0,
     'exports_monitoring_hardware_values_cluster_dragon_six_v': 3457,
     'exports_monitoring_hardware_values_cluster_dragon_tp_injection': 2397,
     'exports_monitoring_hardware_values_cluster_dragon_tp_rate': 2397,
     'exports_monitoring_hardware_values_cluster_enabled': 2397,
     'exports_monitoring_hardware_values_cluster_error': 0,
     'exports_monitoring_hardware_values_cluster_l0_majority': 2397,
     'exports_monitoring_hardware_values_cluster_l0_sate': 0,
     'exports_monitoring_hardware_values_cluster_l0_sum': 2397,
     'exports_monitoring_hardware_values_cluster_l1_adder': 7167,
     'exports_monitoring_hardware_values_cluster_l1_dac_threshold_default': 7167,
     'exports_monitoring_hardware_values_cluster_l1_dac_threshold_set': 7167,
     'exports_monitoring_hardware_values_cluster_l1_extern_rate': 2397,
     'exports_monitoring_hardware_values_cluster_l1_rate': 2397,
     'exports_monitoring_hardware_values_cluster_l1_rate_low': 2397,
     'exports_monitoring_hardware_values_cluster_l1_state': 2397,
     'exports_monitoring_hardware_values_cluster_majority_enabled': 0,
     'exports_monitoring_hardware_values_cluster_number': 0,
     'exports_monitoring_hardware_values_cluster_port': 2397,
     'exports_monitoring_hardware_values_cluster_scb_flag': 2397,
     'exports_monitoring_hardware_values_cluster_scb_humidity': 10185,
     'exports_monitoring_hardware_values_cluster_scb_hw_version': 0,
     'exports_monitoring_hardware_values_cluster_scb_id_code': 0,
     'exports_monitoring_hardware_values_cluster_scb_pmask': 2397,
     'exports_monitoring_hardware_values_cluster_scb_pmt_current': 2397,
     'exports_monitoring_hardware_values_cluster_scb_sw_version': 2397,
     'exports_monitoring_hardware_values_cluster_scb_temperature': 6821,
     'exports_monitoring_hardware_values_cluster_scb_testpulse_enabled': 2397,
     'exports_monitoring_hardware_values_cluster_scb_uid': 0,
     'exports_monitoring_hardware_values_cluster_state': 0,
     'exports_monitoring_hardware_values_cluster_sum_enabled': 0,
     'exports_monitoring_hardware_values_cluster_sw_version': 0,
     'exports_monitoring_hardware_values_cluster_tp_rate': 0,
     'exports_monitoring_hardware_values_pixel_AN_current': 0,
     'exports_monitoring_hardware_values_pixel_clipping_bias': 0,
     'exports_monitoring_hardware_values_pixel_clipping_sel': 0,
     'exports_monitoring_hardware_values_pixel_delay': 0,
     'exports_monitoring_hardware_values_pixel_dt': 0,
     'exports_monitoring_hardware_values_pixel_enabled': 17562,
     'exports_monitoring_hardware_values_pixel_error': 17562,
     'exports_monitoring_hardware_values_pixel_gain': 0,
     'exports_monitoring_hardware_values_pixel_l0_asic_main_register': 69969,
     'exports_monitoring_hardware_values_pixel_l0_clipping_bias': 17562,
     'exports_monitoring_hardware_values_pixel_l0_clipping_sel': 17562,
     'exports_monitoring_hardware_values_pixel_l0_delay': 24982,
     'exports_monitoring_hardware_values_pixel_l0_dt': 17562,
     'exports_monitoring_hardware_values_pixel_l0_gain': 17562,
     'exports_monitoring_hardware_values_pixel_l0_ipr': 69969,
     'exports_monitoring_hardware_values_pixel_l0_on': 17562,
     'exports_monitoring_hardware_values_pixel_l0_rate': 0,
     'exports_monitoring_hardware_values_pixel_l0_threshold_register': 0,
     'exports_monitoring_hardware_values_pixel_pixel_error': 0,
     'exports_monitoring_hardware_values_pixel_scb_amplifier_id_code': 0,
     'exports_monitoring_hardware_values_pixel_scb_an_current': 99649,
     'exports_monitoring_hardware_values_pixel_scb_hotcold': 35031,
     'exports_monitoring_hardware_values_pixel_scb_hv_default': 24982,
     'exports_monitoring_hardware_values_pixel_scb_hv_monitored': 99649,
     'exports_monitoring_hardware_values_pixel_scb_hv_set': 24982,
     'exports_monitoring_hardware_values_pixel_scb_pcode': 17562,
     'exports_monitoring_hardware_values_pixel_scb_pixel_temperature': 0,
     'exports_monitoring_hardware_values_pixel_scb_temperature': 24982,
     'exports_monitoring_hardware_values_pixel_scb_tp_boost': 17562,
     'exports_monitoring_hardware_values_pixel_scb_tp_gain': 17562,
     'exports_monitoring_hardware_values_pixel_tp_boost': 0,
     'exports_monitoring_number_of_cluster': 0,
     'exports_monitoring_number_of_clusters': 0,
     'exports_monitoring_state': 0,
     'exports_monitoring_version': 127}


    # Creating a dictionary to store the information
    event_dict = {}
    for key in dict_caco_states.keys():
        event_dict[key] = np.repeat(0, len(timespans_dict[key]["tstart"]))
    
    # Taking the main collections and chunks pointers
    property_collection = client_tcu['bridgesmonitoring']['properties']
    chunk_collection = client_tcu['bridgesmonitoring']['chunks']
    
    _property = query_property
    print(f"Finding data of property {_property}...")
    descriptors = property_collection.find({'property_name': _property})

    for desc in descriptors:
        for state in dict_caco_states.keys():

            if state not in ["nada"]:
                print(f"Extracting for state {state} : {dict_caco_states[state]}")
                # print(f"The number of timespans is -> {len(timespans_dict[state]['tstart'])}")
    
                # Then running for all the timespans
                for i in range(len(timespans_dict[state]["tstart"]))[:]:
    
                    _tstart = timespans_dict[state]["tstart"][i]
                    _tstop  = timespans_dict[state]["tstop"][i]
                    # _center_time = _tstart + (_tstop - _tstart) / 2
                    # _timespan = (_tstop - _tstart).total_seconds()
    
                    # print(f"From {_tstart} to {_tstop}, a total of {_timespan:.0f} seconds")
                    print(f"Running over timespans... {i}/{len(timespans_dict[state]['tstart'])}") if i% 400 == 0 else None
                    
                    query = {'pid': desc['_id']}
                    query.update({"begin": {"$gte": _tstart}, "end": {"$lte": _tstop}})
    
                    number_chunks = chunk_collection.count_documents(query)
    
                    # event_dict[state]['timestamp'].append(_center_time)
                    event_dict[state][i] += number_chunks * dict_tcu_property_bytes[_property]

    # Saving the object
    with open(f"objects/tmp/event_dict_property_{query_property}.pkl", "wb") as f:
        pickle.dump(event_dict, f, pickle.HIGHEST_PROTOCOL)

if __name__ == "__main__":
    input_str = sys.argv[1]
    main(input_str)